import Link from "next/link";
import { Control } from "./Control";
import "./globals.css";

// 웹사이트 title 서버 컴포넌트에서만 가능
export const metadata = {
  title: "Web",
  description: "Generated by create next app",
};

// async 추가
export default async function RootLayout({ children }) {
  // 서버 컴포넌트
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + 'topics', { cache: 'no-store' });
  const topics = await resp.json();

  // 처음 받아온 캐시를 삭제해야 데이터가 업데이트 되는데 제공해주는 Revalidatiog Data 사용하거나
  // 간단하게 받아온 후 캐시를 만들지 않는 것 { next: { revalidata: 10 } } 공식문서에 다 있음
  // { next: { revalidata: 10 } }: 10초 동안만 캐시를 유지하겠다.
  // { next: { revalidata: 0 } }
  // { cache: 'no-store' }: 캐시를 저장하지 않는다. 

  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map((topic) => {
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
